### PR TITLE
Remove + if dirty

### PR DESCRIPTION
**Pull request by sisuresh**
### What

If the submodule is dirty, then the hashes returned by `git submodule status` will be prefixed with a `+` and cause the PR to fail.

### CODE REVIEW

**Review by graydon — APPROVED** [review]

**Comment by leighmcculloch** [comment]
I'm surprised that caused the PR to fail. Thanks for fixing. The intent for keeping it originally was that it would be obvious if the repo was dirty.

**Comment by leighmcculloch** [comment]
Wait, why would a submodule be dirty in a PR? The submodule in the PR should always be up to date.

**Comment by sisuresh** [comment]
This was actually always a problem for me, but I would just remove the `+` manually. It sounds like you don't run into this because you commit the submodule change and then run `make clean generate`?

**Comment by leighmcculloch** [comment]
Ah, so this was an error you were experiencing locally, or in the PR in CI?

**Comment by sisuresh** [comment]
The error would happen in CI. [This](https://github.com/stellar/rs-stellar-xdr/actions/runs/4813483107/jobs/8570061941) is what that looked like.

**Comment by leighmcculloch** [comment]
That error is intended. It's important that a PR fails if the PR is not in a state that we'd want merged. If the submodule in this repo is dirty, the PR shouldn't be mergeable. 

Am I missing something about it?

**Comment by sisuresh** [comment]
So are you saying my process to update xdr is incorrect? eg. I should update the submodule -> commit -> run `make clean generate` -> commit? I currently update the submodule -> run `make clean generate` -> commit.

**Comment by leighmcculloch** [comment]
Ah, so I guess it doesn't matter then. You're right.

**Pull request merged**
