### PR TITLE
Add stellar-xdr bin

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Add a stellar-xdr binary to the stellar-xdr crate that can decode XDR using the XDR in the crate.

Also make it possible to import the lib crate with both XDRs, which is now the default, and specifying feature `curr` or `next` results in current behavior.

### Why
So that every release of stellar-xdr is accompanied by a tool that can decode XDR created by the crate.

I initially created this tool separately, but it occurred to me that unless it is inside this crate, there will be versions of this crate that don't have a corresponding CLI that can decode XDR. It would be convenient if this is true though.

The CLI dependencies and code are added behind a feature such that they do not pollute the dependency graph of anyone importing the crate for typical library usage.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
The thing I don't like about this current design is that you have to install a different tool for curr, next, or different versions of the XDR that are embedded. Ideally you install the tool once and you can access them all.

**Comment by tomerweller** [comment]
Not a blocker but It would be great to have this functionality reflected in the README

**Comment by leighmcculloch** [comment]
> Not a blocker but It would be great to have this functionality reflected in the README

Good call, thanks. I've improved the readme and docs.rs docs.

**Review by graydon — APPROVED** [review]

**Comment by leighmcculloch** [comment]
Some example uses:

Parse a transaction:
```
echo -n 'AAAAAgAAAAAALj6rZVmMG3ABkGRfUfcENfNmkrrwkQHWMi8uqGuMyAAD0JUClZKPAAAV9gAAAAEAAAAAAAAAAAAAAABjh77jAAAAAAAAAAEAAAABAAAAAA9r7nDrYQRR+K0OSjlNgO1wjfnKb3xZXfmz2F4+yHtEAAAADAAAAAAAAAACZUNIQUlOAAAAAAAAAAAAAPBZ6x4O1QjX/RB2zEBwQ8lxIf/Qka8o4bbDOIr6bXyjAAAALQR7+8gAAAUNAExLPwAAAABCsNfjAAAAAAAAAAI+yHtEAAAAQGzZL8oOd4bdb+KT6ZMdyLSg4z2wpNICCHv8tnKmZKUMv8qFzn5XkhvEtMlJ3qBqaOl022lIEaVVa7BnvHi02AKoa4zIAAAAQFgQl1aootdWkdszkHfJCZxqTSXzoDYys8J6usXfQ7EK5ZKsiXTI5aOorv8CiAxx9SrIX3585ArsD3DgVsx+JgY=' \
| stellar-xdr decode --type TransactionEnvelope
```

Parse a spec stream from a contract:
```
echo -n 'AAAAAgAAAAAAAAAHRGF0YUtleQAAAAACAAAAB0NvdW50ZXIAAAAAAQAAB9AAAAAKSWRlbnRpZmllcgAAAAAABU5vbmNlAAAAAAAAAQAAB9AAAAAKSWRlbnRpZmllcgAAAAAABAAAAAAAAAAFRXJyb3IAAAAAAAACAAAAGEluY29ycmVjdE5vbmNlRm9ySW52b2tlcgAAAAEAAAAOSW5jb3JyZWN0Tm9uY2UAAAAAAAIAAAAAAAAACWluY3JlbWVudAAAAAAAAAIAAAADc2lnAAAAB9AAAAAJU2lnbmF0dXJlAAAAAAAABW5vbmNlAAAAAAAACgAAAAEAAAABAAAAAAAAAAVub25jZQAAAAAAAAEAAAACaWQAAAAAB9AAAAAKSWRlbnRpZmllcgAAAAAAAQAAAAoAAAABAAAADHNvcm9iYW5fYXV0aAAAABBFZDI1NTE5U2lnbmF0dXJlAAAAAgAAAApwdWJsaWNfa2V5AAAAAAPuAAAAIAAAAAlzaWduYXR1cmUAAAAAAAPuAAAAQAAAAAEAAAAMc29yb2Jhbl9hdXRoAAAAEUFjY291bnRTaWduYXR1cmVzAAAAAAAAAgAAAAphY2NvdW50X2lkAAAAAAAMAAAACnNpZ25hdHVyZXMAAAAAA+oAAAfQAAAAEEVkMjU1MTlTaWduYXR1cmUAAAACAAAADHNvcm9iYW5fYXV0aAAAAAlTaWduYXR1cmUAAAAAAAADAAAAB0ludm9rZXIAAAAAAAAAAAdFZDI1NTE5AAAAAAEAAAfQAAAAEEVkMjU1MTlTaWduYXR1cmUAAAAHQWNjb3VudAAAAAABAAAH0AAAABFBY2NvdW50U2lnbmF0dXJlcwAAAAAAAAIAAAAMc29yb2Jhbl9hdXRoAAAACklkZW50aWZpZXIAAAAAAAMAAAAIQ29udHJhY3QAAAABAAAD7gAAACAAAAAHRWQyNTUxOQAAAAABAAAD7gAAACAAAAAHQWNjb3VudAAAAAABAAAADAAAAAEAAAAMc29yb2Jhbl9hdXRoAAAAElNpZ25hdHVyZVBheWxvYWRWMAAAAAAABAAAAAduZXR3b3JrAAAAAAkAAAAIY29udHJhY3QAAAPuAAAAIAAAAARuYW1lAAAABgAAAARhcmdzAAAD6gAAAAAAAAACAAAADHNvcm9iYW5fYXV0aAAAABBTaWduYXR1cmVQYXlsb2FkAAAAAQAAAAJWMAAAAAAAAQAAB9AAAAASU2lnbmF0dXJlUGF5bG9hZFYwAAA=' \
| stellar-xdr +next decode --type ScSpecEntry --input stream-base64 --output json-formatted
```

Parse a bucket:
```
stellar-xdr decode --type BucketEntry --input stream-framed --output json-formatted buckets/bucket-2fe17964e8dc12b2db37679fe05e541e040b4d75b2855ce6f283831c964b878f.xdr
```

**Pull request merged**
