### PR TITLE
CAP-52 XDR

### PR DESCRIPTION
**Pull request by jonjove**
### What

Add the XDR for CAP-52, specifically `InvokeHostFunctionOp`.

### Why

Required to support CAP-52 in stellar/rs-stellar-contract-env and stellar/stellar-core.

### Known limitations

N/A

### CODE REVIEW

**Comment by jonjove** [comment]
@leighmcculloch it took me a while to get all the PRs open, but it corresponds to changes in https://github.com/stellar/stellar-core/pull/3450 and https://github.com/stellar/rs-stellar-contract-env/pull/112. I don't know how we want to sequence these merges.

**Comment by leighmcculloch** [comment]
@jonjove I think if you want to be strict about it, you should break up stellar/stellar-core#3450 to be two PRs, one that modifies the XDR first, and then one that makes any changes that are dependent on the `stellar-env-host` crate. Then the process would be:
- Modify XDR.
- Update rs-stellar-xdr.
- Update rs-stellar-env-host.
- Update stellar-core.

We may as well have the XDR in its own repo. cc @MonsieurNicolas 

@graydon How did you do this recently?

**Comment by leighmcculloch** [comment]
Until we figure this out I think it's fine if you merge this just before merging the stellar-core PR, assuming the .x files are identical.

**Review by leighmcculloch — APPROVED** [review]

**Review by graydon — CHANGES_REQUESTED** [review]
I left a comment in the accompanying core XDR change that I think the return from the function should have an SCVal and so this would need to be regenerated to match if so. Otherwise ok.

**Comment by jonjove** [comment]
@graydon I left a long [comment](https://github.com/stellar/stellar-core/pull/3450#discussion_r898041956) explaining why I don't think we should have the `SCVal`.

**Pull request merged**
